services:
  FreshScannerBot:
    build: .
    image: fresh-scanner-bot
    ports:
      - "8000:8000"
    environment:
      TZ: Europe/Moscow
    env_file:
      - .env
    volumes:
      - ./fresh_scanner.db:/bot/fresh_scanner.db
